import random

#img hug
img_hug = ["https://c.tenor.com/9e1aE_xBLCsAAAAC/anime-hug.gif", "https://c.tenor.com/Ct4bdr2ZGeAAAAAC/teria-wang-kishuku-gakkou-no-juliet.gif", "https://c.tenor.com/4n3T2I239q8AAAAC/anime-cute.gif", "https://c.tenor.com/ztEJgrjFe54AAAAC/hug-anime.gif", "https://c.tenor.com/2lr9uM5JmPQAAAAC/hug-anime-hug.gif", "https://c.tenor.com/0vl21YIsGvgAAAAC/hug-anime.gif", "https://c.tenor.com/ItpTQW2UKPYAAAAC/cuddle-hug.gif", "https://c.tenor.com/SXk-WqF6PpQAAAAC/anime-hug.gif", "https://c.tenor.com/X5nBTYuoKpoAAAAC/anime-cheeks.gif", "https://c.tenor.com/SPs0Rpt7HAcAAAAC/chiya-urara.gif", "https://c.tenor.com/mmQyXP3JvKwAAAAC/anime-cute.gif", "https://c.tenor.com/jQ0FcfbsXqIAAAAC/hug-anime.gif", "https://c.tenor.com/z2QaiBZCLCQAAAAC/hug-anime.gif", "https://c.tenor.com/ixaDEFhZJSsAAAAC/anime-choke.gif", "https://c.tenor.com/vkiqyZJWJ4wAAAAC/hug-cat.gif", "https://c.tenor.com/UhcyGsGpLNIAAAAC/hug-anime.gif", "https://c.tenor.com/nmzZIEFv8nkAAAAC/hug-anime.gif", "https://c.tenor.com/sBFE3GeNpJ4AAAAC/tackle-hug-couple.gif", "https://c.tenor.com/WpbZhwwj6zAAAAAC/happy-hug.gif", "https://c.tenor.com/EnfEuWDXthkAAAAC/hug-couple.gif"]


#img hello"
img_hi = ["https://c.tenor.com/S6Kxbixp1yUAAAAC/gakkou-gurashi-hello.gif", "https://c.tenor.com/Ch4VFEjuI7IAAAAC/anime-boy.gif", "https://c.tenor.com/B8PvHQ3BhuoAAAAd/kakashi-kakashi-hatake.gif", "https://c.tenor.com/OSnZnnqx4vsAAAAC/anime-hello.gif", "https://c.tenor.com/_Exw4V_izbkAAAAC/cute-anime.gif", "https://c.tenor.com/thNxDWlG1EcAAAAd/killua-zoldyck-anime.gif", "https://c.tenor.com/qC7wW2hY52YAAAAC/anime-ons.gif", "https://c.tenor.com/eeyZsVwZScsAAAAd/anime-wave.gif", "https://c.tenor.com/-KgmJMneKM8AAAAC/hello-anime.gif", "https://c.tenor.com/Hntke7HWHhIAAAAC/wave-anime.gif", "https://c.tenor.com/jsIMbsjcZ4YAAAAC/kawaii-anime.gif", "https://c.tenor.com/dessgik7ovcAAAAC/anime-wave.gif", "https://c.tenor.com/DDnp-TLMTWQAAAAC/hello-anime.gif", "https://c.tenor.com/EERR4LXoJBoAAAAd/hi-wave.gif", "https://c.tenor.com/aszBCTeb7XsAAAAC/hello-t%C5%8Dru-oikawa.gif", "https://c.tenor.com/yUveohNfdfQAAAAC/hello-anime.gif", "https://c.tenor.com/OoQlWsxH2SEAAAAC/hi-anime-hello.gif", "https://c.tenor.com/g0QIOyhPLRQAAAAC/neon_cove-cute.gif", "https://c.tenor.com/qix2X5XHZ74AAAAC/kuga-yuma-world-trigger.gif"]

print(f"Hug: {len(random.choice(img_hug))};")
print(f"Hi: {len(random.choice(img_hi))};")
